# Generated by Django 4.2.1 on 2023-05-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_user_mail', models.EmailField(max_length=254)),
                ('comment_music_id', models.TextField()),
                ('comment_good', models.IntegerField()),
                ('comment_text', models.TextField()),
                ('comment_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_user_mail', models.EmailField(max_length=254)),
                ('history_music_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LikeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_user_mail', models.EmailField(max_length=254)),
                ('like_music_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('music_id', models.TextField(primary_key=True, serialize=False)),
                ('music_star', models.IntegerField()),
                ('music_ad', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_comment_id', models.IntegerField()),
                ('result_user_mail', models.EmailField(max_length=254)),
                ('result_text', models.TextField()),
                ('result_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=50)),
                ('user_mail', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('user_pass', models.CharField(max_length=30)),
                ('user_image', models.ImageField(upload_to='images/')),
                ('user_birthday', models.DateField()),
            ],
        ),
    ]
